import {defineAdditionalConfig, type DefaultTheme} from 'vitepress'
import projectInfo from '../.vitepress/info.mjs'

export default defineAdditionalConfig({
  description: 'Sharp Code, In Your Hands.',

  themeConfig: {
    // nav: nav(),

    search: {options: searchOptions()},

    sidebar: {
      '/': {base: '/en/', items: sidebarGuide()},
    },

    editLink: {
      pattern: `${projectInfo.githubUrl}/edit/main/docs/:path`,
      text: 'Edit this page on GitHub'
    },

    footer: {
      message: `Released under the <a href="${projectInfo.githubUrl}/blob/main/LICENSE" target="_blank">MIT License</a>.`,
      copyright: `Copyright © 2025-present <a href="${projectInfo.githubUrl}" target="_blank">${projectInfo.name}</a>`
    },

    docFooter: {
      prev: 'Previous page',
      next: 'Next page'
    },

    outline: {
      label: 'On this page'
    },

    lastUpdated: {
      text: 'Last updated'
    },

    notFound: {
      title: 'PAGE NOT FOUND',
      quote: 'But if you don\'t change your direction, and if you keep looking, you may end up where you are heading.',
      linkLabel: 'Take me home',
      linkText: 'Take me home'
    },

    langMenuLabel: 'Language',
    returnToTopLabel: 'Back to Top',
    sidebarMenuLabel: 'Menu',
    darkModeSwitchLabel: 'Theme',
    lightModeSwitchTitle: 'Switch to Light Mode',
    darkModeSwitchTitle: 'Switch to Dark Mode',
    skipToContentLabel: 'Skip to Content'
  }
})

function sidebarGuide(): DefaultTheme.SidebarItem[] {
  return [
    {
      text: 'Quick Start',
      collapsed: false,
      items: [
        {text: 'Introduce', link: 'introduce'},
        {text: 'Installation', link: 'installation'}
      ]
    },
    {
      text: 'Packages',
      collapsed: false,
      items: [
        {text: 'Entity', link: 'package/entity'},
        {text: 'Url', link: 'package/url'},
        {text: 'Path', link: 'package/path'},
      ]
    }
  ]
}

function searchOptions(): Partial<DefaultTheme.AlgoliaSearchOptions> {
  return {
    placeholder: 'Search',
    translations: {
      button: {
        buttonText: 'Search',
        buttonAriaLabel: 'Search'
      },
      modal: {
        searchBox: {
          clearButtonTitle: 'Clear search criteria',
          clearButtonAriaLabel: 'Clear search criteria',
          closeButtonText: 'Close',
          closeButtonAriaLabel: 'Close',
          placeholderText: 'Search',
          placeholderTextAskAi: 'Ask AI:',
          placeholderTextAskAiStreaming: 'Answering...',
          searchInputLabel: 'Search',
          backToKeywordSearchButtonText: 'Back to keyword search',
          backToKeywordSearchButtonAriaLabel: 'Back to keyword search'
        },
        startScreen: {
          recentSearchesTitle: 'Search History',
          noRecentSearchesText: 'No search history',
          saveRecentSearchButtonTitle: 'Save to search history',
          removeRecentSearchButtonTitle: 'Remove from search history',
          favoriteSearchesTitle: 'Favorites',
          removeFavoriteSearchButtonTitle: 'Remove from favorites',
          recentConversationsTitle: 'Recent Conversations',
          removeRecentConversationButtonTitle: 'Delete conversation from history'
        },
        errorScreen: {
          titleText: 'Unable to get results',
          helpText: 'You may need to check your network connection'
        },
        noResultsScreen: {
          noResultsText: 'No relevant results found',
          suggestedQueryText: 'You can try searching for',
          reportMissingResultsText: 'Do you think there should be results for this query?',
          reportMissingResultsLinkText: 'Click to give feedback'
        },
        resultsScreen: {
          askAiPlaceholder: 'Ask AI: '
        },
        askAiScreen: {
          disclaimerText: 'Answers are generated by AI and may not be accurate. Please verify independently.',
          relatedSourcesText: 'Related Sources',
          thinkingText: 'Thinking...',
          copyButtonText: 'Copy',
          copyButtonCopiedText: 'Copied!',
          copyButtonTitle: 'Copy',
          likeButtonTitle: 'Like',
          dislikeButtonTitle: 'Dislike',
          thanksForFeedbackText: 'Thank you for your feedback!',
          preToolCallText: 'Searching...',
          duringToolCallText: 'Searching ',
          afterToolCallText: 'Searched',
          aggregatedToolCallText: 'Searched'
        },
        footer: {
          selectText: 'Select',
          submitQuestionText: 'Submit Question',
          selectKeyAriaLabel: 'Enter key',
          navigateText: 'Navigate',
          navigateUpKeyAriaLabel: 'Up arrow',
          navigateDownKeyAriaLabel: 'Down arrow',
          closeText: 'Close',
          backToSearchText: 'Back to search',
          closeKeyAriaLabel: 'Esc key',
          poweredByText: 'Powered by'
        }
      }
    }
  }
}
